spring:
  zipkin:
    # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://zipkin/
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
       #  默认值为0.1f，现在为了测试设置100%采集
      probability: 1.0

  # 数据源相关配置
  datasource:
    username: root
    password: lanboal
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF8&useSSL=false
    dbcp2:
      max-total: 10
      min-idle: 2
      max-idle: 5



server:
  port: 8881

# 设置Refresh容器时不需要安全校验
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

# Ribbon的其他配置信息, 见 {@link RibbonClientConfiguration#ribbonClientConfig()}  和 {@link DefaultClientConfigImpl}
ribbon:
  MaxAutoRetriesNextServer: 2

# ribbon应用配置信息, 详见 {@link PropertiesFactory}
bank-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


