spring:
  application:
    #代表项目里文件名称的前缀：bank-account
    name: bank-account

server:
  port: 8881

# 设置Refresh容器时不需要安全校验
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

# Ribbon的其他配置信息, 见 {@link RibbonClientConfiguration#ribbonClientConfig()}  和 {@link DefaultClientConfigImpl}
ribbon:
  MaxAutoRetriesNextServer: 2

# ribbon应用配置信息, 详见 {@link PropertiesFactory}
bank-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule





#http请求地址和资源文件映射如下
#/{application}/{profile}[/{label}]

#/{application}-{profile}.yml

#/{label}/{application}-{profile}.yml

#/{application}-{profile}.properties

#/{label}/{application}-{profile}.properties