spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiangJibo/bank-config/
          searchPaths:
          username:
          password:
        prefix: bank/config
      label: master

  application:
    name: bank-config

server:
  port: 8888

# 设置Refresh容器时不需要安全校验
management:
  security:
    enabled: false




#Client的http请求地址和资源文件映射如下,
# application.name：代表子应用的名称
# profile：子应用的配置环境
# label: git上的项目分支

#/{application.name}/{profile}[/{label}]

#/{application.name}-{profile}.yml

#/{label}/{application.name}-{profile}.yml

#/{application.name}-{profile}.properties

#/{label}/{application.name}-{profile}.properties